export const Default = () => `
    <footer class="acg-footer">
        <div class="acg-footer__content">
            <a href="#" class="acg-footer__logo">
                <img alt="Arch Capital logo" src="assets/arch-logo-sm.png">
            </a>
            <nav class="acg-footer__nav" aria-label="Arch footer navigation">
            <!-- Generated by WP  -->
                <div class="menu-footer-container">
                    <ul id="menu-footer" class="acg-menu acg-footer__menu">
                        <li class="acg-menu__item acg-menu__item--1">
                          <span class="acg-footer__label">Arch Capital Group</span>
                            <ul class="acg-menu acg-footer__menu__submenu">
                                <li class="acg-menu__item"><a href="#">About Arch</a></li>
                                <li class="acg-menu__item"><a href="#">Leadership</a></li>
                                <li class="acg-menu__item"><a href="#">Insights</a></li>
                                <li class="acg-menu__item"><a href="#">Sustainability</a></li>
                                <li class="acg-menu__item"><a href="#">Claims</a></li>
                            </ul>
                        </li>
                        <li class="acg-menu__item acg-menu__item--2">
                          <span class="acg-footer__label">Quick Links</span>
                            <ul class="acg-menu acg-footer__menu__submenu">
                                <li class="acg-menu__item"><a href="#">Financial Strength</a></li>
                                <li class="acg-menu__item"><a href="#">Careers</a></li>
                                <li class="acg-menu__item"><a href="#">Investor Relations</a></li>
                                <li class="acg-menu__item"><a href="#">Arch in the News</a></li>
                            </ul>
                        </li>
                        <li class="acg-menu__item acg-menu__item--3">
                          <span class="acg-footer__label">Arch Corporate</span>
                            <ul class="acg-menu acg-footer__menu__submenu">
                                <li class="acg-menu__item"><a href="#">Investors</a></li>
                                <li class="acg-menu__item"><a href="#">Media Relations</a></li>
                            </ul>
                        </li>
                        <li class="acg-menu__item acg-menu__item--4">
                          <span class="acg-footer__label">Arch Directories</span>
                            <ul class="acg-menu acg-footer__menu__submenu">
                                <li class="acg-menu__item"><a href="#">Find a Contact</a></li>
                                <li class="acg-menu__item"><a href="#">Locations</a></li>
                            </ul>
                            <span class="acg-footer__label">Connect with Us</span>
                            <div class="acg-footer__icons">
                              <a href="#" target="_blank" ref="noopener noreferrer" class="acg-footer__icons__link"><i focusable="false" class="fab fa-linkedin-in" title="LinkedIn"></i><span class="acg-accessibly-hidden">LinkedIn</span></a>
                              <a href="#" target="_blank" ref="noopener noreferrer" class="acg-footer__icons__link"><i focusable="false" class="fab fa-facebook-f" title="Facebook"></i><span class="acg-accessibly-hidden">Facebook</span></a>
                              <a href="#" target="_blank" ref="noopener noreferrer" class="acg-footer__icons__link"><i focusable="false" class="fab fa-instagram" title="Instagram"></i><span class="acg-accessibly-hidden">Instagram</span></a>
                            </div>
                        </li>
                    </ul>
                </div>
            <!-- End Generated by WP  -->
            </nav>
        </div>

        <div class="acg-footer__below acg-footer__blue">
            <div class="acg-footer__content">
                <nav class="acg-footer__privacy-links">
					<p class="acg-type-body--xsmall acg-type-style--bold">About Arch Capital Group</p>
					<ul class="acg-menu acg-footer__menu-privacy acg-menu--footer-global">
	    		        <li class="acg-menu__item  menu-item menu-item-type-post_type menu-item-object-page">
			                <a href="#" class="acg-menu__item__link" target="">Office Locations</a>
					    </li>
	    		        <li class="acg-menu__item  menu-item menu-item-type-post_type menu-item-object-page">
			                <a href="#" class="acg-menu__item__link" target="">Purpose and Values</a>
                        </li>
                        <li class="acg-menu__item  menu-item menu-item-type-post_type menu-item-object-page">
                            <a href="#" class="acg-menu__item__link" target="">Sustainability &amp; Governance</a>
					    </li>
		            </ul>

                    <ul class="acg-menu acg-footer__menu-privacy acg-menu--footer-privacy">
	    		        <li class="acg-menu__item  menu-item menu-item-type-post_type menu-item-object-page">
			                <a href="#" class="acg-menu__item__link" target="">Terms &amp; Conditions</a>
					    </li>
	    		        <li class="acg-menu__item  menu-item menu-item-type-post_type menu-item-object-page menu-item-privacy-policy">
			                <a href="#" class="acg-menu__item__link" target="">Privacy Policy</a>
					    </li>
	    		        <li class="acg-menu__item  menu-item menu-item-type-post_type menu-item-object-page">
			                <a href="#" class="acg-menu__item__link" target="">Cookie Policy</a>
					    </li>
		            </ul>
				</nav>
                <span class="acg-footer__fine-print">&copy;2021 Arch Capital Group Ltd.</span>
            </div>
        </div>

    </footer>
`;
